spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: xxooroutes
          #          uri: http://81.69.193.138:8848
          uri: lb://consumer
          predicates:
            - Path=/loadBalance/demo/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
    nacos:
      discovery:
        server-addr: 81.69.193.138:8848
  redis:
    host: 81.69.193.138
    port: 6379
    database: 0

server:
  port: 8088

consumer:
  ribbon:
    NFLoadBalancerRuleClassName: com.example.gateway.loadBalance.MyRule


